name: actions-homework
on:
  pull_request: 
    types: [ assigned, opened, synchronize, reopened ]
jobs: 
  echo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "This is our first Github Workflow!"
